<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>rttest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SoulsFormats\SoulsFormats\SoulsFormats.csproj" />
    <ProjectReference Include="..\DS1MegaRando.Core\DS1MegaRando.Core.csproj" />
    <ProjectReference Include="..\DS1MegaRando.Data\DS1MegaRando.Data.csproj" />
  </ItemGroup>
</Project>
