<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="YamlDotNet" Version="15.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DS1MegaRando.Data\DS1MegaRando.Data.csproj" />
    <ProjectReference Include="..\SoulsFormats\SoulsFormats\SoulsFormats.csproj" />
  </ItemGroup>

</Project>
