<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>DS1Mod.Core</RootNamespace>
    <AssemblyName>DS1Mod.Core</AssemblyName>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
