using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Data;
using Avalonia.Data.Core;
using Avalonia.Data.Core.Plugins;
using Avalonia.Input;
using Avalonia.Layout;
using Avalonia.Markup.Xaml.Converters;
using Avalonia.Markup.Xaml.MarkupExtensions;
using Avalonia.Markup.Xaml.MarkupExtensions.CompiledBindings;
using Avalonia.Markup.Xaml.XamlIl.Runtime;
using Avalonia.Media;
using Avalonia.ReactiveUI;
using CompiledAvaloniaXaml;
using DS1Randomizer.ViewModels;
using RandomizerCommon.ViewModels;
using ReactiveUI;

namespace DS1Randomizer.Views
{
	// Token: 0x0200000F RID: 15
	[NullableContext(1)]
	[Nullable(new byte[]
	{
		0,
		1
	})]
	[CompilerGenerated]
	public class MainWindow : ReactiveWindow<MainWindowViewModel>
	{
		// Token: 0x06000029 RID: 41 RVA: 0x000022B0 File Offset: 0x000004B0
		public MainWindow()
		{
			this.InitializeComponent(true);
			if (Design.IsDesignMode)
			{
				return;
			}
			this.WhenActivated(delegate(Action<IDisposable> action)
			{
				action(base.ViewModel.ShowOptionsDialog.RegisterHandler(new Func<IInteractionContext<OptionsViewModel, OptionsViewModel.Result>, Task>(this.DoShowOptionsDialog)));
			});
			this.WhenActivated(delegate(Action<IDisposable> action)
			{
				action(base.ViewModel.ShowMergeModDialog.RegisterHandler(new Func<IInteractionContext<MergeModViewModel, string>, Task>(this.DoShowMergeModDialog)));
			});
			this.WhenActivated(delegate(Action<IDisposable> action)
			{
				action(base.ViewModel.ShowDllDialog.RegisterHandler(new Func<IInteractionContext<DllViewModel, ImmutableList<string>>, Task>(this.DoShowDllDialog)));
			});
		}

		// Token: 0x0600002A RID: 42 RVA: 0x0000230C File Offset: 0x0000050C
		private Task DoShowOptionsDialog([Nullable(new byte[]
		{
			1,
			1,
			2
		})] IInteractionContext<OptionsViewModel, OptionsViewModel.Result> interaction)
		{
			MainWindow.<DoShowOptionsDialog>d__1 <DoShowOptionsDialog>d__;
			<DoShowOptionsDialog>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
			<DoShowOptionsDialog>d__.<>4__this = this;
			<DoShowOptionsDialog>d__.interaction = interaction;
			<DoShowOptionsDialog>d__.<>1__state = -1;
			<DoShowOptionsDialog>d__.<>t__builder.Start<MainWindow.<DoShowOptionsDialog>d__1>(ref <DoShowOptionsDialog>d__);
			return <DoShowOptionsDialog>d__.<>t__builder.Task;
		}

		// Token: 0x0600002B RID: 43 RVA: 0x00002358 File Offset: 0x00000558
		private Task DoShowMergeModDialog([Nullable(new byte[]
		{
			1,
			1,
			2
		})] IInteractionContext<MergeModViewModel, string> interaction)
		{
			MainWindow.<DoShowMergeModDialog>d__2 <DoShowMergeModDialog>d__;
			<DoShowMergeModDialog>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
			<DoShowMergeModDialog>d__.<>4__this = this;
			<DoShowMergeModDialog>d__.interaction = interaction;
			<DoShowMergeModDialog>d__.<>1__state = -1;
			<DoShowMergeModDialog>d__.<>t__builder.Start<MainWindow.<DoShowMergeModDialog>d__2>(ref <DoShowMergeModDialog>d__);
			return <DoShowMergeModDialog>d__.<>t__builder.Task;
		}

		// Token: 0x0600002C RID: 44 RVA: 0x000023A4 File Offset: 0x000005A4
		private Task DoShowDllDialog([Nullable(new byte[]
		{
			1,
			1,
			2,
			1
		})] IInteractionContext<DllViewModel, ImmutableList<string>> interaction)
		{
			MainWindow.<DoShowDllDialog>d__3 <DoShowDllDialog>d__;
			<DoShowDllDialog>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
			<DoShowDllDialog>d__.<>4__this = this;
			<DoShowDllDialog>d__.interaction = interaction;
			<DoShowDllDialog>d__.<>1__state = -1;
			<DoShowDllDialog>d__.<>t__builder.Start<MainWindow.<DoShowDllDialog>d__3>(ref <DoShowDllDialog>d__);
			return <DoShowDllDialog>d__.<>t__builder.Task;
		}

		// Token: 0x0600002D RID: 45 RVA: 0x000023F0 File Offset: 0x000005F0
		[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.2.7.0")]
		[ExcludeFromCodeCoverage]
		public void InitializeComponent(bool loadXaml = true)
		{
			if (loadXaml)
			{
				MainWindow.!XamlIlPopulateTrampoline(this);
			}
			INameScope nameScope = this.FindNameScope();
			this.message = ((nameScope != null) ? nameScope.Find("message") : null);
			this.status = ((nameScope != null) ? nameScope.Find("status") : null);
		}

		// Token: 0x06000031 RID: 49 RVA: 0x000024A8 File Offset: 0x000006A8
		private static void !XamlIlPopulate(IServiceProvider A_0, MainWindow A_1)
		{
			XamlIlContext.Context<MainWindow> context = new XamlIlContext.Context<MainWindow>(A_0, new object[]
			{
				(object)CompiledAvaloniaXaml.!AvaloniaResources.NamespaceInfo:/Views/MainWindow.axaml.Singleton
			}, "avares://DS1Randomizer/Views/MainWindow.axaml");
			context.RootObject = A_1;
			context.IntermediateRoot = A_1;
			((ISupportInitialize)A_1).BeginInit();
			context.PushParent(A_1);
			A_1.Icon = (WindowIcon)new IconTypeConverter().ConvertFrom(context, CultureInfo.InvariantCulture, "/Assets/flask.ico");
			A_1.Width = 1050.0;
			A_1.Height = 670.0;
			A_1.MinWidth = 1050.0;
			A_1.MinHeight = 670.0;
			AvaloniaProperty titleProperty = Window.TitleProperty;
			CompiledBindingExtension compiledBindingExtension = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Title!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider = context;
			context.ProvideTargetProperty = Window.TitleProperty;
			IBinding binding = compiledBindingExtension.ProvideValue(provider);
			context.ProvideTargetProperty = null;
			A_1.Bind(titleProperty, binding, null);
			ResourceDictionary resourceDictionary;
			IResourceDictionary resources = resourceDictionary = new ResourceDictionary();
			context.PushParent(resourceDictionary);
			resourceDictionary.MergedDictionaries.Add(CompiledAvaloniaXaml.!AvaloniaResources.Build:/Assets/MainResources.axaml(XamlIlRuntimeHelpers.CreateRootServiceProviderV3(context)));
			context.PopParent();
			A_1.Resources = resources;
			A_1.Styles.Add(CompiledAvaloniaXaml.!AvaloniaResources.Build:/Styles/MainStyles.axaml(XamlIlRuntimeHelpers.CreateRootServiceProviderV3(context)));
			Grid grid2;
			Grid grid = grid2 = new Grid();
			((ISupportInitialize)grid).BeginInit();
			A_1.Content = grid;
			Grid grid3;
			ISupportInitialize supportInitialize = grid3 = grid2;
			context.PushParent(grid3);
			Grid grid4 = grid3;
			ColumnDefinitions columnDefinitions = new ColumnDefinitions();
			columnDefinitions.Capacity = 1;
			columnDefinitions.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
			grid4.ColumnDefinitions = columnDefinitions;
			RowDefinitions rowDefinitions = new RowDefinitions();
			rowDefinitions.Capacity = 4;
			rowDefinitions.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions.Add(new RowDefinition(new GridLength(1.0, GridUnitType.Star)));
			rowDefinitions.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			grid4.RowDefinitions = rowDefinitions;
			AvaloniaList<Control> children = grid4.Children;
			Menu menu2;
			Menu menu = menu2 = new Menu();
			((ISupportInitialize)menu).BeginInit();
			children.Add(menu);
			Menu menu3;
			ISupportInitialize supportInitialize2 = menu3 = menu2;
			context.PushParent(menu3);
			Menu menu4 = menu3;
			Grid.SetColumn(menu4, 0);
			Grid.SetRow(menu4, 0);
			ItemCollection items = menu4.Items;
			MenuItem menuItem2;
			MenuItem menuItem = menuItem2 = new MenuItem();
			((ISupportInitialize)menuItem).BeginInit();
			items.Add(menuItem);
			MenuItem menuItem3;
			ISupportInitialize supportInitialize3 = menuItem3 = menuItem2;
			context.PushParent(menuItem3);
			MenuItem menuItem4 = menuItem3;
			menuItem4.Header = "_File";
			ItemCollection items2 = menuItem4.Items;
			MenuItem menuItem6;
			MenuItem menuItem5 = menuItem6 = new MenuItem();
			((ISupportInitialize)menuItem5).BeginInit();
			items2.Add(menuItem5);
			ISupportInitialize supportInitialize4 = menuItem3 = menuItem6;
			context.PushParent(menuItem3);
			MenuItem menuItem7 = menuItem3;
			menuItem7.Header = "Restore game directory backups...";
			AvaloniaProperty commandProperty = MenuItem.CommandProperty;
			CompiledBindingExtension compiledBindingExtension2 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.UninstallCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider2 = context;
			context.ProvideTargetProperty = MenuItem.CommandProperty;
			IBinding binding2 = compiledBindingExtension2.ProvideValue(provider2);
			context.ProvideTargetProperty = null;
			menuItem7.Bind(commandProperty, binding2, null);
			context.PopParent();
			supportInitialize4.EndInit();
			ItemCollection items3 = menuItem4.Items;
			Separator separator2;
			Separator separator = separator2 = new Separator();
			((ISupportInitialize)separator).BeginInit();
			items3.Add(separator);
			((ISupportInitialize)separator2).EndInit();
			ItemCollection items4 = menuItem4.Items;
			MenuItem menuItem9;
			MenuItem menuItem8 = menuItem9 = new MenuItem();
			((ISupportInitialize)menuItem8).BeginInit();
			items4.Add(menuItem8);
			ISupportInitialize supportInitialize5 = menuItem3 = menuItem9;
			context.PushParent(menuItem3);
			MenuItem menuItem10 = menuItem3;
			menuItem10.Header = "Check for updates on Nexus Mods";
			AvaloniaProperty commandProperty2 = MenuItem.CommandProperty;
			CompiledBindingExtension compiledBindingExtension3 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.CheckUpdatesCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider3 = context;
			context.ProvideTargetProperty = MenuItem.CommandProperty;
			IBinding binding3 = compiledBindingExtension3.ProvideValue(provider3);
			context.ProvideTargetProperty = null;
			menuItem10.Bind(commandProperty2, binding3, null);
			context.PopParent();
			supportInitialize5.EndInit();
			context.PopParent();
			supportInitialize3.EndInit();
			ItemCollection items5 = menu4.Items;
			MenuItem menuItem12;
			MenuItem menuItem11 = menuItem12 = new MenuItem();
			((ISupportInitialize)menuItem11).BeginInit();
			items5.Add(menuItem11);
			ISupportInitialize supportInitialize6 = menuItem3 = menuItem12;
			context.PushParent(menuItem3);
			MenuItem menuItem13 = menuItem3;
			menuItem13.Header = "_Settings";
			ItemCollection items6 = menuItem13.Items;
			MenuItem menuItem15;
			MenuItem menuItem14 = menuItem15 = new MenuItem();
			((ISupportInitialize)menuItem14).BeginInit();
			items6.Add(menuItem14);
			ISupportInitialize supportInitialize7 = menuItem3 = menuItem15;
			context.PushParent(menuItem3);
			MenuItem menuItem16 = menuItem3;
			menuItem16.Header = "Set options from string...";
			AvaloniaProperty commandProperty3 = MenuItem.CommandProperty;
			CompiledBindingExtension compiledBindingExtension4 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Command("ImportOptions", new Action<object, object>(XamlIlTrampolines.DS1Randomizer:DS1Randomizer.ViewModels.MainWindowViewModel+ImportOptions_0!CommandExecuteTrampoline), null, null).Build());
			IServiceProvider provider4 = context;
			context.ProvideTargetProperty = MenuItem.CommandProperty;
			IBinding binding4 = compiledBindingExtension4.ProvideValue(provider4);
			context.ProvideTargetProperty = null;
			menuItem16.Bind(commandProperty3, binding4, null);
			context.PopParent();
			supportInitialize7.EndInit();
			ItemCollection items7 = menuItem13.Items;
			MenuItem menuItem18;
			MenuItem menuItem17 = menuItem18 = new MenuItem();
			((ISupportInitialize)menuItem17).BeginInit();
			items7.Add(menuItem17);
			ISupportInitialize supportInitialize8 = menuItem3 = menuItem18;
			context.PushParent(menuItem3);
			MenuItem menuItem19 = menuItem3;
			menuItem19.Header = "Reset options";
			AvaloniaProperty commandProperty4 = MenuItem.CommandProperty;
			CompiledBindingExtension compiledBindingExtension5 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.ResetOptionsCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider5 = context;
			context.ProvideTargetProperty = MenuItem.CommandProperty;
			IBinding binding5 = compiledBindingExtension5.ProvideValue(provider5);
			context.ProvideTargetProperty = null;
			menuItem19.Bind(commandProperty4, binding5, null);
			context.PopParent();
			supportInitialize8.EndInit();
			ItemCollection items8 = menuItem13.Items;
			Separator separator4;
			Separator separator3 = separator4 = new Separator();
			((ISupportInitialize)separator3).BeginInit();
			items8.Add(separator3);
			((ISupportInitialize)separator4).EndInit();
			ItemCollection items9 = menuItem13.Items;
			MenuItem menuItem21;
			MenuItem menuItem20 = menuItem21 = new MenuItem();
			((ISupportInitialize)menuItem20).BeginInit();
			items9.Add(menuItem20);
			ISupportInitialize supportInitialize9 = menuItem3 = menuItem21;
			context.PushParent(menuItem3);
			MenuItem menuItem22 = menuItem3;
			menuItem22.Header = "Toggle dark mode";
			AvaloniaProperty commandProperty5 = MenuItem.CommandProperty;
			CompiledBindingExtension compiledBindingExtension6 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.ToggleDarkModeCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider6 = context;
			context.ProvideTargetProperty = MenuItem.CommandProperty;
			IBinding binding6 = compiledBindingExtension6.ProvideValue(provider6);
			context.ProvideTargetProperty = null;
			menuItem22.Bind(commandProperty5, binding6, null);
			context.PopParent();
			supportInitialize9.EndInit();
			context.PopParent();
			supportInitialize6.EndInit();
			context.PopParent();
			supportInitialize2.EndInit();
			AvaloniaList<Control> children2 = grid4.Children;
			Grid grid6;
			Grid grid5 = grid6 = new Grid();
			((ISupportInitialize)grid5).BeginInit();
			children2.Add(grid5);
			ISupportInitialize supportInitialize10 = grid3 = grid6;
			context.PushParent(grid3);
			Grid grid7 = grid3;
			Grid.SetColumn(grid7, 0);
			Grid.SetRow(grid7, 1);
			grid7.Margin = new Thickness(5.0, 5.0, 5.0, 5.0);
			ColumnDefinitions columnDefinitions2 = new ColumnDefinitions();
			columnDefinitions2.Capacity = 3;
			columnDefinitions2.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
			columnDefinitions2.Add(new ColumnDefinition(new GridLength(7.0, GridUnitType.Pixel)));
			columnDefinitions2.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
			grid7.ColumnDefinitions = columnDefinitions2;
			RowDefinitions rowDefinitions2 = new RowDefinitions();
			rowDefinitions2.Capacity = 3;
			rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions2.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			grid7.RowDefinitions = rowDefinitions2;
			AvaloniaList<Control> children3 = grid7.Children;
			HeaderedContentControl headeredContentControl2;
			HeaderedContentControl headeredContentControl = headeredContentControl2 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl).BeginInit();
			children3.Add(headeredContentControl);
			HeaderedContentControl headeredContentControl3;
			ISupportInitialize supportInitialize11 = headeredContentControl3 = headeredContentControl2;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl4 = headeredContentControl3;
			headeredContentControl4.Header = "Boss placement";
			Grid.SetColumn(headeredContentControl4, 0);
			Grid.SetRow(headeredContentControl4, 0);
			headeredContentControl4.Classes.Add("groupbox");
			StackPanel stackPanel2;
			StackPanel stackPanel = stackPanel2 = new StackPanel();
			((ISupportInitialize)stackPanel).BeginInit();
			headeredContentControl4.Content = stackPanel;
			StackPanel stackPanel3;
			ISupportInitialize supportInitialize12 = stackPanel3 = stackPanel2;
			context.PushParent(stackPanel3);
			StackPanel stackPanel4 = stackPanel3;
			AvaloniaList<Control> children4 = stackPanel4.Children;
			CheckBox checkBox2;
			CheckBox checkBox = checkBox2 = new CheckBox();
			((ISupportInitialize)checkBox).BeginInit();
			children4.Add(checkBox);
			CheckBox checkBox3;
			ISupportInitialize supportInitialize13 = checkBox3 = checkBox2;
			context.PushParent(checkBox3);
			CheckBox checkBox4 = checkBox3;
			AvaloniaProperty isCheckedProperty = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension7 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Simpleasylum!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider7 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding7 = compiledBindingExtension7.ProvideValue(provider7);
			context.ProvideTargetProperty = null;
			checkBox4.Bind(isCheckedProperty, binding7, null);
			checkBox4.Content = "Make Asylum Demon a simple boss";
			context.PopParent();
			supportInitialize13.EndInit();
			AvaloniaList<Control> children5 = stackPanel4.Children;
			CheckBox checkBox6;
			CheckBox checkBox5 = checkBox6 = new CheckBox();
			((ISupportInitialize)checkBox5).BeginInit();
			children5.Add(checkBox5);
			ISupportInitialize supportInitialize14 = checkBox3 = checkBox6;
			context.PushParent(checkBox3);
			CheckBox checkBox7 = checkBox3;
			AvaloniaProperty isCheckedProperty2 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension8 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Simpletaurus!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider8 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding8 = compiledBindingExtension8.ProvideValue(provider8);
			context.ProvideTargetProperty = null;
			checkBox7.Bind(isCheckedProperty2, binding8, null);
			checkBox7.Content = "Make Taurus Demon a simple boss";
			context.PopParent();
			supportInitialize14.EndInit();
			context.PopParent();
			supportInitialize12.EndInit();
			context.PopParent();
			supportInitialize11.EndInit();
			AvaloniaList<Control> children6 = grid7.Children;
			HeaderedContentControl headeredContentControl6;
			HeaderedContentControl headeredContentControl5 = headeredContentControl6 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl5).BeginInit();
			children6.Add(headeredContentControl5);
			ISupportInitialize supportInitialize15 = headeredContentControl3 = headeredContentControl6;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl7 = headeredContentControl3;
			headeredContentControl7.Header = "Scaling";
			Grid.SetColumn(headeredContentControl7, 2);
			Grid.SetRow(headeredContentControl7, 0);
			headeredContentControl7.Classes.Add("groupbox");
			StackPanel stackPanel6;
			StackPanel stackPanel5 = stackPanel6 = new StackPanel();
			((ISupportInitialize)stackPanel5).BeginInit();
			headeredContentControl7.Content = stackPanel5;
			ISupportInitialize supportInitialize16 = stackPanel3 = stackPanel6;
			context.PushParent(stackPanel3);
			StackPanel stackPanel7 = stackPanel3;
			AvaloniaList<Control> children7 = stackPanel7.Children;
			RadioButton radioButton2;
			RadioButton radioButton = radioButton2 = new RadioButton();
			((ISupportInitialize)radioButton).BeginInit();
			children7.Add(radioButton);
			RadioButton radioButton3;
			ISupportInitialize supportInitialize17 = radioButton3 = radioButton2;
			context.PushParent(radioButton3);
			RadioButton radioButton4 = radioButton3;
			AvaloniaProperty isCheckedProperty3 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension9 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Scale_default!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider9 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding9 = compiledBindingExtension9.ProvideValue(provider9);
			context.ProvideTargetProperty = null;
			radioButton4.Bind(isCheckedProperty3, binding9, null);
			radioButton4.Content = "Scale enemies up and down based on area (same overall difficulty)";
			context.PopParent();
			supportInitialize17.EndInit();
			AvaloniaList<Control> children8 = stackPanel7.Children;
			RadioButton radioButton6;
			RadioButton radioButton5 = radioButton6 = new RadioButton();
			((ISupportInitialize)radioButton5).BeginInit();
			children8.Add(radioButton5);
			ISupportInitialize supportInitialize18 = radioButton3 = radioButton6;
			context.PushParent(radioButton3);
			RadioButton radioButton7 = radioButton3;
			AvaloniaProperty isCheckedProperty4 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension10 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Noscale!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider10 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding10 = compiledBindingExtension10.ProvideValue(provider10);
			context.ProvideTargetProperty = null;
			radioButton7.Bind(isCheckedProperty4, binding10, null);
			radioButton7.Content = "Don't scale enemies (harder in early game, easier in late game)";
			context.PopParent();
			supportInitialize18.EndInit();
			AvaloniaList<Control> children9 = stackPanel7.Children;
			RadioButton radioButton9;
			RadioButton radioButton8 = radioButton9 = new RadioButton();
			((ISupportInitialize)radioButton8).BeginInit();
			children9.Add(radioButton8);
			ISupportInitialize supportInitialize19 = radioButton3 = radioButton9;
			context.PushParent(radioButton3);
			RadioButton radioButton10 = radioButton3;
			AvaloniaProperty isCheckedProperty5 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension11 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Scaleup!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider11 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding11 = compiledBindingExtension11.ProvideValue(provider11);
			context.ProvideTargetProperty = null;
			radioButton10.Bind(isCheckedProperty5, binding11, null);
			radioButton10.Content = "Don't scale enemies down (harder in early game, same in late game)";
			context.PopParent();
			supportInitialize19.EndInit();
			AvaloniaList<Control> children10 = stackPanel7.Children;
			CheckBox checkBox9;
			CheckBox checkBox8 = checkBox9 = new CheckBox();
			((ISupportInitialize)checkBox8).BeginInit();
			children10.Add(checkBox8);
			ISupportInitialize supportInitialize20 = checkBox3 = checkBox9;
			context.PushParent(checkBox3);
			CheckBox checkBox10 = checkBox3;
			AvaloniaProperty isCheckedProperty6 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension12 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Earlyscale!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider12 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding12 = compiledBindingExtension12.ProvideValue(provider12);
			context.ProvideTargetProperty = null;
			checkBox10.Bind(isCheckedProperty6, binding12, null);
			checkBox10.Content = "Scale tutorial enemies and boss no matter what";
			context.PopParent();
			supportInitialize20.EndInit();
			context.PopParent();
			supportInitialize16.EndInit();
			context.PopParent();
			supportInitialize15.EndInit();
			AvaloniaList<Control> children11 = grid7.Children;
			HeaderedContentControl headeredContentControl9;
			HeaderedContentControl headeredContentControl8 = headeredContentControl9 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl8).BeginInit();
			children11.Add(headeredContentControl8);
			ISupportInitialize supportInitialize21 = headeredContentControl3 = headeredContentControl9;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl10 = headeredContentControl3;
			headeredContentControl10.Header = "Gravelord Black Phantoms";
			Grid.SetColumn(headeredContentControl10, 0);
			Grid.SetRow(headeredContentControl10, 1);
			headeredContentControl10.Classes.Add("groupbox");
			StackPanel stackPanel9;
			StackPanel stackPanel8 = stackPanel9 = new StackPanel();
			((ISupportInitialize)stackPanel8).BeginInit();
			headeredContentControl10.Content = stackPanel8;
			ISupportInitialize supportInitialize22 = stackPanel3 = stackPanel9;
			context.PushParent(stackPanel3);
			StackPanel stackPanel10 = stackPanel3;
			AvaloniaList<Control> children12 = stackPanel10.Children;
			RadioButton radioButton12;
			RadioButton radioButton11 = radioButton12 = new RadioButton();
			((ISupportInitialize)radioButton11).BeginInit();
			children12.Add(radioButton11);
			ISupportInitialize supportInitialize23 = radioButton3 = radioButton12;
			context.PushParent(radioButton3);
			RadioButton radioButton13 = radioButton3;
			AvaloniaProperty isCheckedProperty7 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension13 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Gravelord_default!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider13 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding13 = compiledBindingExtension13.ProvideValue(provider13);
			context.ProvideTargetProperty = null;
			radioButton13.Bind(isCheckedProperty7, binding13, null);
			radioButton13.Content = "Gravelord a random map every 10 minutes";
			context.PopParent();
			supportInitialize23.EndInit();
			AvaloniaList<Control> children13 = stackPanel10.Children;
			RadioButton radioButton15;
			RadioButton radioButton14 = radioButton15 = new RadioButton();
			((ISupportInitialize)radioButton14).BeginInit();
			children13.Add(radioButton14);
			ISupportInitialize supportInitialize24 = radioButton3 = radioButton15;
			context.PushParent(radioButton3);
			RadioButton radioButton16 = radioButton3;
			AvaloniaProperty isCheckedProperty8 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension14 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Permagravelord!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider14 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding14 = compiledBindingExtension14.ProvideValue(provider14);
			context.ProvideTargetProperty = null;
			radioButton16.Bind(isCheckedProperty8, binding14, null);
			radioButton16.Content = "Permagravelord all maps";
			context.PopParent();
			supportInitialize24.EndInit();
			AvaloniaList<Control> children14 = stackPanel10.Children;
			RadioButton radioButton18;
			RadioButton radioButton17 = radioButton18 = new RadioButton();
			((ISupportInitialize)radioButton17).BeginInit();
			children14.Add(radioButton17);
			ISupportInitialize supportInitialize25 = radioButton3 = radioButton18;
			context.PushParent(radioButton3);
			RadioButton radioButton19 = radioButton3;
			AvaloniaProperty isCheckedProperty9 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension15 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Nogravelord!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider15 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding15 = compiledBindingExtension15.ProvideValue(provider15);
			context.ProvideTargetProperty = null;
			radioButton19.Bind(isCheckedProperty9, binding15, null);
			radioButton19.Content = "Disable gravelording maps";
			context.PopParent();
			supportInitialize25.EndInit();
			context.PopParent();
			supportInitialize22.EndInit();
			context.PopParent();
			supportInitialize21.EndInit();
			AvaloniaList<Control> children15 = grid7.Children;
			HeaderedContentControl headeredContentControl12;
			HeaderedContentControl headeredContentControl11 = headeredContentControl12 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl11).BeginInit();
			children15.Add(headeredContentControl11);
			ISupportInitialize supportInitialize26 = headeredContentControl3 = headeredContentControl12;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl13 = headeredContentControl3;
			headeredContentControl13.Header = "Evil Vagrants";
			Grid.SetColumn(headeredContentControl13, 2);
			Grid.SetRow(headeredContentControl13, 1);
			headeredContentControl13.Classes.Add("groupbox");
			StackPanel stackPanel12;
			StackPanel stackPanel11 = stackPanel12 = new StackPanel();
			((ISupportInitialize)stackPanel11).BeginInit();
			headeredContentControl13.Content = stackPanel11;
			ISupportInitialize supportInitialize27 = stackPanel3 = stackPanel12;
			context.PushParent(stackPanel3);
			StackPanel stackPanel13 = stackPanel3;
			AvaloniaList<Control> children16 = stackPanel13.Children;
			RadioButton radioButton21;
			RadioButton radioButton20 = radioButton21 = new RadioButton();
			((ISupportInitialize)radioButton20).BeginInit();
			children16.Add(radioButton20);
			ISupportInitialize supportInitialize28 = radioButton3 = radioButton21;
			context.PushParent(radioButton3);
			RadioButton radioButton22 = radioButton3;
			AvaloniaProperty isCheckedProperty10 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension16 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Vagrant_default!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider16 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding16 = compiledBindingExtension16.ProvideValue(provider16);
			context.ProvideTargetProperty = null;
			radioButton22.Bind(isCheckedProperty10, binding16, null);
			radioButton22.Content = "Randomly spawn enemies which replace evil vagrants";
			context.PopParent();
			supportInitialize28.EndInit();
			AvaloniaList<Control> children17 = stackPanel13.Children;
			RadioButton radioButton24;
			RadioButton radioButton23 = radioButton24 = new RadioButton();
			((ISupportInitialize)radioButton23).BeginInit();
			children17.Add(radioButton23);
			ISupportInitialize supportInitialize29 = radioButton3 = radioButton24;
			context.PushParent(radioButton3);
			RadioButton radioButton25 = radioButton3;
			AvaloniaProperty isCheckedProperty11 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension17 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Permavagrant!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider17 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding17 = compiledBindingExtension17.ProvideValue(provider17);
			context.ProvideTargetProperty = null;
			radioButton25.Bind(isCheckedProperty11, binding17, null);
			radioButton25.Content = "Always spawn enemies which replace evil vagrants";
			context.PopParent();
			supportInitialize29.EndInit();
			AvaloniaList<Control> children18 = stackPanel13.Children;
			CheckBox checkBox12;
			CheckBox checkBox11 = checkBox12 = new CheckBox();
			((ISupportInitialize)checkBox11).BeginInit();
			children18.Add(checkBox11);
			ISupportInitialize supportInitialize30 = checkBox3 = checkBox12;
			context.PushParent(checkBox3);
			CheckBox checkBox13 = checkBox3;
			AvaloniaProperty isCheckedProperty12 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension18 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Limitvagrant!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider18 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding18 = compiledBindingExtension18.ProvideValue(provider18);
			context.ProvideTargetProperty = null;
			checkBox13.Bind(isCheckedProperty12, binding18, null);
			checkBox13.Content = "Reduce frequency of randomized evil vagrants";
			context.PopParent();
			supportInitialize30.EndInit();
			context.PopParent();
			supportInitialize27.EndInit();
			context.PopParent();
			supportInitialize26.EndInit();
			AvaloniaList<Control> children19 = grid7.Children;
			HeaderedContentControl headeredContentControl15;
			HeaderedContentControl headeredContentControl14 = headeredContentControl15 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl14).BeginInit();
			children19.Add(headeredContentControl14);
			ISupportInitialize supportInitialize31 = headeredContentControl3 = headeredContentControl15;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl16 = headeredContentControl3;
			headeredContentControl16.Header = "Miscellaneous";
			Grid.SetColumn(headeredContentControl16, 0);
			Grid.SetRow(headeredContentControl16, 2);
			headeredContentControl16.Classes.Add("groupbox");
			StackPanel stackPanel15;
			StackPanel stackPanel14 = stackPanel15 = new StackPanel();
			((ISupportInitialize)stackPanel14).BeginInit();
			headeredContentControl16.Content = stackPanel14;
			ISupportInitialize supportInitialize32 = stackPanel3 = stackPanel15;
			context.PushParent(stackPanel3);
			StackPanel stackPanel16 = stackPanel3;
			AvaloniaList<Control> children20 = stackPanel16.Children;
			CheckBox checkBox15;
			CheckBox checkBox14 = checkBox15 = new CheckBox();
			((ISupportInitialize)checkBox14).BeginInit();
			children20.Add(checkBox14);
			ISupportInitialize supportInitialize33 = checkBox3 = checkBox15;
			context.PushParent(checkBox3);
			CheckBox checkBox16 = checkBox3;
			AvaloniaProperty isCheckedProperty13 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension19 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Editnames!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider19 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding19 = compiledBindingExtension19.ProvideValue(provider19);
			context.ProvideTargetProperty = null;
			checkBox16.Bind(isCheckedProperty13, binding19, null);
			checkBox16.Content = "Edit boss names";
			context.PopParent();
			supportInitialize33.EndInit();
			AvaloniaList<Control> children21 = stackPanel16.Children;
			CheckBox checkBox18;
			CheckBox checkBox17 = checkBox18 = new CheckBox();
			((ISupportInitialize)checkBox17).BeginInit();
			children21.Add(checkBox17);
			ISupportInitialize supportInitialize34 = checkBox3 = checkBox18;
			context.PushParent(checkBox3);
			CheckBox checkBox19 = checkBox3;
			AvaloniaProperty isCheckedProperty14 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension20 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Antighost!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider20 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding20 = compiledBindingExtension20.ProvideValue(provider20);
			context.ProvideTargetProperty = null;
			checkBox19.Bind(isCheckedProperty14, binding20, null);
			checkBox19.Content = "Make ghosts always tangible";
			context.PopParent();
			supportInitialize34.EndInit();
			AvaloniaList<Control> children22 = stackPanel16.Children;
			CheckBox checkBox21;
			CheckBox checkBox20 = checkBox21 = new CheckBox();
			((ISupportInitialize)checkBox20).BeginInit();
			children22.Add(checkBox20);
			ISupportInitialize supportInitialize35 = checkBox3 = checkBox21;
			context.PushParent(checkBox3);
			CheckBox checkBox22 = checkBox3;
			AvaloniaProperty isCheckedProperty15 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension21 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Impolite!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider21 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding21 = compiledBindingExtension21.ProvideValue(provider21);
			context.ProvideTargetProperty = null;
			checkBox22.Bind(isCheckedProperty15, binding21, null);
			checkBox22.Content = "Impolite enemies";
			context.PopParent();
			supportInitialize35.EndInit();
			context.PopParent();
			supportInitialize32.EndInit();
			context.PopParent();
			supportInitialize31.EndInit();
			AvaloniaList<Control> children23 = grid7.Children;
			HeaderedContentControl headeredContentControl18;
			HeaderedContentControl headeredContentControl17 = headeredContentControl18 = new HeaderedContentControl();
			((ISupportInitialize)headeredContentControl17).BeginInit();
			children23.Add(headeredContentControl17);
			ISupportInitialize supportInitialize36 = headeredContentControl3 = headeredContentControl18;
			context.PushParent(headeredContentControl3);
			HeaderedContentControl headeredContentControl19 = headeredContentControl3;
			headeredContentControl19.Header = "Files";
			Grid.SetColumn(headeredContentControl19, 2);
			Grid.SetRow(headeredContentControl19, 2);
			headeredContentControl19.Classes.Add("groupbox");
			StackPanel stackPanel18;
			StackPanel stackPanel17 = stackPanel18 = new StackPanel();
			((ISupportInitialize)stackPanel17).BeginInit();
			headeredContentControl19.Content = stackPanel17;
			ISupportInitialize supportInitialize37 = stackPanel3 = stackPanel18;
			context.PushParent(stackPanel3);
			StackPanel stackPanel19 = stackPanel3;
			AvaloniaList<Control> children24 = stackPanel19.Children;
			CheckBox checkBox24;
			CheckBox checkBox23 = checkBox24 = new CheckBox();
			((ISupportInitialize)checkBox23).BeginInit();
			children24.Add(checkBox23);
			ISupportInitialize supportInitialize38 = checkBox3 = checkBox24;
			context.PushParent(checkBox3);
			CheckBox checkBox25 = checkBox3;
			AvaloniaProperty isCheckedProperty16 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension22 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Crashfix!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider22 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding22 = compiledBindingExtension22.ProvideValue(provider22);
			context.ProvideTargetProperty = null;
			checkBox25.Bind(isCheckedProperty16, binding22, null);
			checkBox25.Content = "Use crash fix dll";
			context.PopParent();
			supportInitialize38.EndInit();
			AvaloniaList<Control> children25 = stackPanel19.Children;
			CheckBox checkBox27;
			CheckBox checkBox26 = checkBox27 = new CheckBox();
			((ISupportInitialize)checkBox26).BeginInit();
			children25.Add(checkBox26);
			ISupportInitialize supportInitialize39 = checkBox3 = checkBox27;
			context.PushParent(checkBox3);
			CheckBox checkBox28 = checkBox3;
			AvaloniaProperty isCheckedProperty17 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension23 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Mergegame!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider23 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding23 = compiledBindingExtension23.ProvideValue(provider23);
			context.ProvideTargetProperty = null;
			checkBox28.Bind(isCheckedProperty17, binding23, null);
			checkBox28.Content = "Merge files from game directory";
			context.PopParent();
			supportInitialize39.EndInit();
			AvaloniaList<Control> children26 = stackPanel19.Children;
			CheckBox checkBox30;
			CheckBox checkBox29 = checkBox30 = new CheckBox();
			((ISupportInitialize)checkBox29).BeginInit();
			children26.Add(checkBox29);
			ISupportInitialize supportInitialize40 = checkBox3 = checkBox30;
			context.PushParent(checkBox3);
			CheckBox checkBox31 = checkBox3;
			AvaloniaProperty isCheckedProperty18 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension24 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Loose!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider24 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding24 = compiledBindingExtension24.ProvideValue(provider24);
			context.ProvideTargetProperty = null;
			checkBox31.Bind(isCheckedProperty18, binding24, null);
			checkBox31.Content = "Output files to game directory";
			context.PopParent();
			supportInitialize40.EndInit();
			context.PopParent();
			supportInitialize37.EndInit();
			context.PopParent();
			supportInitialize36.EndInit();
			context.PopParent();
			supportInitialize10.EndInit();
			AvaloniaList<Control> children27 = grid4.Children;
			Grid grid9;
			Grid grid8 = grid9 = new Grid();
			((ISupportInitialize)grid8).BeginInit();
			children27.Add(grid8);
			ISupportInitialize supportInitialize41 = grid3 = grid9;
			context.PushParent(grid3);
			Grid grid10 = grid3;
			grid10.Margin = new Thickness(5.0, 5.0, 5.0, 5.0);
			Grid.SetColumn(grid10, 0);
			Grid.SetRow(grid10, 2);
			ColumnDefinitions columnDefinitions3 = new ColumnDefinitions();
			columnDefinitions3.Capacity = 4;
			columnDefinitions3.Add(new ColumnDefinition(new GridLength(1.0, GridUnitType.Star)));
			columnDefinitions3.Add(new ColumnDefinition(new GridLength(0.0, GridUnitType.Auto)));
			columnDefinitions3.Add(new ColumnDefinition(new GridLength(5.0, GridUnitType.Pixel)));
			columnDefinitions3.Add(new ColumnDefinition(new GridLength(0.0, GridUnitType.Auto)));
			grid10.ColumnDefinitions = columnDefinitions3;
			RowDefinitions rowDefinitions3 = new RowDefinitions();
			rowDefinitions3.Capacity = 9;
			rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(3.0, GridUnitType.Pixel)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(3.0, GridUnitType.Pixel)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(3.0, GridUnitType.Pixel)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(3.0, GridUnitType.Pixel)));
			rowDefinitions3.Add(new RowDefinition(new GridLength(0.0, GridUnitType.Auto)));
			grid10.RowDefinitions = rowDefinitions3;
			grid10.Classes.Add("panel");
			AvaloniaList<Control> children28 = grid10.Children;
			TextBox textBox2;
			TextBox textBox = textBox2 = new TextBox();
			((ISupportInitialize)textBox).BeginInit();
			children28.Add(textBox);
			TextBox textBox3;
			ISupportInitialize supportInitialize42 = textBox3 = textBox2;
			context.PushParent(textBox3);
			TextBox textBox4 = textBox3;
			Grid.SetRow(textBox4, 0);
			Grid.SetColumn(textBox4, 0);
			Grid.SetColumnSpan(textBox4, 2);
			AvaloniaProperty textProperty = TextBox.TextProperty;
			CompiledBindingExtension compiledBindingExtension25 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Exe!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider25 = context;
			context.ProvideTargetProperty = TextBox.TextProperty;
			IBinding binding25 = compiledBindingExtension25.ProvideValue(provider25);
			context.ProvideTargetProperty = null;
			textBox4.Bind(textProperty, binding25, null);
			textBox4.Watermark = "DarkSoulsRemastered.exe path";
			context.PopParent();
			supportInitialize42.EndInit();
			AvaloniaList<Control> children29 = grid10.Children;
			Button button2;
			Button button = button2 = new Button();
			((ISupportInitialize)button).BeginInit();
			children29.Add(button);
			Button button3;
			ISupportInitialize supportInitialize43 = button3 = button2;
			context.PushParent(button3);
			Button button4 = button3;
			Grid.SetRow(button4, 0);
			Grid.SetColumn(button4, 3);
			AvaloniaProperty commandProperty6 = Button.CommandProperty;
			CompiledBindingExtension compiledBindingExtension26 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.SelectExeCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider26 = context;
			context.ProvideTargetProperty = Button.CommandProperty;
			IBinding binding26 = compiledBindingExtension26.ProvideValue(provider26);
			context.ProvideTargetProperty = null;
			button4.Bind(commandProperty6, binding26, null);
			button4.Content = "Select exe";
			context.PopParent();
			supportInitialize43.EndInit();
			AvaloniaList<Control> children30 = grid10.Children;
			TextBox textBox6;
			TextBox textBox5 = textBox6 = new TextBox();
			((ISupportInitialize)textBox5).BeginInit();
			children30.Add(textBox5);
			ISupportInitialize supportInitialize44 = textBox3 = textBox6;
			context.PushParent(textBox3);
			TextBox textBox7 = textBox3;
			Grid.SetRow(textBox7, 2);
			Grid.SetColumn(textBox7, 0);
			Grid.SetColumnSpan(textBox7, 2);
			AvaloniaProperty textProperty2 = TextBox.TextProperty;
			CompiledBindingExtension compiledBindingExtension27 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Mod!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider27 = context;
			context.ProvideTargetProperty = TextBox.TextProperty;
			IBinding binding27 = compiledBindingExtension27.ProvideValue(provider27);
			context.ProvideTargetProperty = null;
			textBox7.Bind(textProperty2, binding27, null);
			textBox7.Watermark = "Other mod path (optional)";
			context.PopParent();
			supportInitialize44.EndInit();
			AvaloniaList<Control> children31 = grid10.Children;
			Button button6;
			Button button5 = button6 = new Button();
			((ISupportInitialize)button5).BeginInit();
			children31.Add(button5);
			ISupportInitialize supportInitialize45 = button3 = button6;
			context.PushParent(button3);
			Button button7 = button3;
			Grid.SetRow(button7, 2);
			Grid.SetColumn(button7, 3);
			AvaloniaProperty commandProperty7 = Button.CommandProperty;
			CompiledBindingExtension compiledBindingExtension28 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.MergeModsCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider28 = context;
			context.ProvideTargetProperty = Button.CommandProperty;
			IBinding binding28 = compiledBindingExtension28.ProvideValue(provider28);
			context.ProvideTargetProperty = null;
			button7.Bind(commandProperty7, binding28, null);
			button7.Content = "Merge other mod";
			context.PopParent();
			supportInitialize45.EndInit();
			AvaloniaList<Control> children32 = grid10.Children;
			TextBlock textBlock2;
			TextBlock textBlock = textBlock2 = new TextBlock();
			((ISupportInitialize)textBlock).BeginInit();
			children32.Add(textBlock);
			TextBlock textBlock3;
			ISupportInitialize supportInitialize46 = textBlock3 = textBlock2;
			context.PushParent(textBlock3);
			TextBlock textBlock4 = textBlock3;
			Grid.SetRow(textBlock4, 4);
			Grid.SetColumn(textBlock4, 0);
			Grid.SetColumnSpan(textBlock4, 2);
			AvaloniaProperty textProperty3 = TextBlock.TextProperty;
			CompiledBindingExtension compiledBindingExtension29 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.DllStr!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider29 = context;
			context.ProvideTargetProperty = TextBlock.TextProperty;
			IBinding binding29 = compiledBindingExtension29.ProvideValue(provider29);
			context.ProvideTargetProperty = null;
			textBlock4.Bind(textProperty3, binding29, null);
			textBlock4.HorizontalAlignment = HorizontalAlignment.Right;
			textBlock4.VerticalAlignment = VerticalAlignment.Center;
			textBlock4.Margin = new Thickness(0.0, 0.0, 2.0, 0.0);
			context.PopParent();
			supportInitialize46.EndInit();
			AvaloniaList<Control> children33 = grid10.Children;
			Button button9;
			Button button8 = button9 = new Button();
			((ISupportInitialize)button8).BeginInit();
			children33.Add(button8);
			ISupportInitialize supportInitialize47 = button3 = button9;
			context.PushParent(button3);
			Button button10 = button3;
			Grid.SetRow(button10, 4);
			Grid.SetColumn(button10, 3);
			AvaloniaProperty commandProperty8 = Button.CommandProperty;
			CompiledBindingExtension compiledBindingExtension30 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.AddDllCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider30 = context;
			context.ProvideTargetProperty = Button.CommandProperty;
			IBinding binding30 = compiledBindingExtension30.ProvideValue(provider30);
			context.ProvideTargetProperty = null;
			button10.Bind(commandProperty8, binding30, null);
			button10.Content = "Add dll mods";
			context.PopParent();
			supportInitialize47.EndInit();
			AvaloniaList<Control> children34 = grid10.Children;
			TextBlock textBlock6;
			TextBlock textBlock5 = textBlock6 = new TextBlock();
			((ISupportInitialize)textBlock5).BeginInit();
			children34.Add(textBlock5);
			ISupportInitialize supportInitialize48 = textBlock3 = textBlock6;
			context.PushParent(textBlock3);
			TextBlock textBlock7 = textBlock3;
			Grid.SetRow(textBlock7, 6);
			Grid.SetColumn(textBlock7, 0);
			Grid.SetRowSpan(textBlock7, 3);
			AvaloniaProperty textProperty4 = TextBlock.TextProperty;
			CompiledBindingExtension compiledBindingExtension31 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Message!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider31 = context;
			context.ProvideTargetProperty = TextBlock.TextProperty;
			IBinding binding31 = compiledBindingExtension31.ProvideValue(provider31);
			context.ProvideTargetProperty = null;
			textBlock7.Bind(textProperty4, binding31, null);
			textBlock7.Name = "message";
			object element = textBlock7;
			context.AvaloniaNameScope.Register("message", element);
			CompiledBindingExtension compiledBindingExtension32 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.MessageError!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider32 = context;
			context.ProvideTargetProperty = "class:error";
			IBinding binding32 = compiledBindingExtension32.ProvideValue(provider32);
			context.ProvideTargetProperty = null;
			IBinding source = binding32;
			textBlock7.BindClass("error", source, null);
			textBlock7.TextWrapping = TextWrapping.WrapWithOverflow;
			textBlock7.MaxHeight = 100.0;
			context.PopParent();
			supportInitialize48.EndInit();
			AvaloniaList<Control> children35 = grid10.Children;
			TextBox textBox9;
			TextBox textBox8 = textBox9 = new TextBox();
			((ISupportInitialize)textBox8).BeginInit();
			children35.Add(textBox8);
			ISupportInitialize supportInitialize49 = textBox3 = textBox9;
			context.PushParent(textBox3);
			TextBox textBox10 = textBox3;
			Grid.SetRow(textBox10, 6);
			Grid.SetColumn(textBox10, 1);
			AvaloniaProperty textProperty5 = TextBox.TextProperty;
			CompiledBindingExtension compiledBindingExtension33 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Seed!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider33 = context;
			context.ProvideTargetProperty = TextBox.TextProperty;
			IBinding binding33 = compiledBindingExtension33.ProvideValue(provider33);
			context.ProvideTargetProperty = null;
			textBox10.Bind(textProperty5, binding33, null);
			textBox10.Watermark = "Seed";
			textBox10.Width = 120.0;
			context.PopParent();
			supportInitialize49.EndInit();
			AvaloniaList<Control> children36 = grid10.Children;
			CheckBox checkBox33;
			CheckBox checkBox32 = checkBox33 = new CheckBox();
			((ISupportInitialize)checkBox32).BeginInit();
			children36.Add(checkBox32);
			ISupportInitialize supportInitialize50 = checkBox3 = checkBox33;
			context.PushParent(checkBox3);
			CheckBox checkBox34 = checkBox3;
			Grid.SetRow(checkBox34, 8);
			Grid.SetColumn(checkBox34, 1);
			AvaloniaProperty isCheckedProperty19 = ToggleButton.IsCheckedProperty;
			CompiledBindingExtension compiledBindingExtension34 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.RerollSeed!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider34 = context;
			context.ProvideTargetProperty = ToggleButton.IsCheckedProperty;
			IBinding binding34 = compiledBindingExtension34.ProvideValue(provider34);
			context.ProvideTargetProperty = null;
			checkBox34.Bind(isCheckedProperty19, binding34, null);
			AvaloniaProperty isEnabledProperty = InputElement.IsEnabledProperty;
			CompiledBindingExtension compiledBindingExtension35 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Not().Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.MustRerollSeed!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider35 = context;
			context.ProvideTargetProperty = InputElement.IsEnabledProperty;
			IBinding binding35 = compiledBindingExtension35.ProvideValue(provider35);
			context.ProvideTargetProperty = null;
			checkBox34.Bind(isEnabledProperty, binding35, null);
			checkBox34.Content = "Reroll seed";
			context.PopParent();
			supportInitialize50.EndInit();
			AvaloniaList<Control> children37 = grid10.Children;
			Button button12;
			Button button11 = button12 = new Button();
			((ISupportInitialize)button11).BeginInit();
			children37.Add(button11);
			ISupportInitialize supportInitialize51 = button3 = button12;
			context.PushParent(button3);
			Button button13 = button3;
			Grid.SetRow(button13, 6);
			Grid.SetColumn(button13, 3);
			CompiledBindingExtension compiledBindingExtension36 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.RandomizeText!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider36 = context;
			context.ProvideTargetProperty = ContentControl.ContentProperty;
			CompiledBindingExtension compiledBindingExtension37 = compiledBindingExtension36.ProvideValue(provider36);
			context.ProvideTargetProperty = null;
			XamlDynamicSetters.<>XamlDynamicSetter_1(button13, compiledBindingExtension37);
			AvaloniaProperty commandProperty9 = Button.CommandProperty;
			CompiledBindingExtension compiledBindingExtension38 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.RandomizeCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider37 = context;
			context.ProvideTargetProperty = Button.CommandProperty;
			IBinding binding36 = compiledBindingExtension38.ProvideValue(provider37);
			context.ProvideTargetProperty = null;
			button13.Bind(commandProperty9, binding36, null);
			CompiledBindingExtension compiledBindingExtension39 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Working!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider38 = context;
			context.ProvideTargetProperty = "class:working";
			IBinding binding37 = compiledBindingExtension39.ProvideValue(provider38);
			context.ProvideTargetProperty = null;
			source = binding37;
			button13.BindClass("working", source, null);
			context.PopParent();
			supportInitialize51.EndInit();
			AvaloniaList<Control> children38 = grid10.Children;
			Button button15;
			Button button14 = button15 = new Button();
			((ISupportInitialize)button14).BeginInit();
			children38.Add(button14);
			ISupportInitialize supportInitialize52 = button3 = button15;
			context.PushParent(button3);
			Button button16 = button3;
			Grid.SetRow(button16, 8);
			Grid.SetColumn(button16, 3);
			AvaloniaProperty commandProperty10 = Button.CommandProperty;
			CompiledBindingExtension compiledBindingExtension40 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.LaunchGameCommand!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider39 = context;
			context.ProvideTargetProperty = Button.CommandProperty;
			IBinding binding38 = compiledBindingExtension40.ProvideValue(provider39);
			context.ProvideTargetProperty = null;
			button16.Bind(commandProperty10, binding38, null);
			CompiledBindingExtension compiledBindingExtension41 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Launching!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider40 = context;
			context.ProvideTargetProperty = "class:working";
			IBinding binding39 = compiledBindingExtension41.ProvideValue(provider40);
			context.ProvideTargetProperty = null;
			source = binding39;
			button16.BindClass("working", source, null);
			button16.Content = "Launch DS1";
			context.PopParent();
			supportInitialize52.EndInit();
			context.PopParent();
			supportInitialize41.EndInit();
			AvaloniaList<Control> children39 = grid4.Children;
			TextBlock textBlock9;
			TextBlock textBlock8 = textBlock9 = new TextBlock();
			((ISupportInitialize)textBlock8).BeginInit();
			children39.Add(textBlock8);
			ISupportInitialize supportInitialize53 = textBlock3 = textBlock9;
			context.PushParent(textBlock3);
			TextBlock textBlock10 = textBlock3;
			Grid.SetColumn(textBlock10, 0);
			Grid.SetRow(textBlock10, 3);
			textBlock10.Name = "status";
			element = textBlock10;
			context.AvaloniaNameScope.Register("status", element);
			CompiledBindingExtension compiledBindingExtension42 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.StatusFailure!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider41 = context;
			context.ProvideTargetProperty = "class:failure";
			IBinding binding40 = compiledBindingExtension42.ProvideValue(provider41);
			context.ProvideTargetProperty = null;
			source = binding40;
			textBlock10.BindClass("failure", source, null);
			CompiledBindingExtension compiledBindingExtension43 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.StatusSuccess!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider42 = context;
			context.ProvideTargetProperty = "class:success";
			IBinding binding41 = compiledBindingExtension43.ProvideValue(provider42);
			context.ProvideTargetProperty = null;
			source = binding41;
			textBlock10.BindClass("success", source, null);
			textBlock10.Padding = new Thickness(5.0, 5.0, 5.0, 5.0);
			AvaloniaProperty textProperty6 = TextBlock.TextProperty;
			CompiledBindingExtension compiledBindingExtension44 = new CompiledBindingExtension(new CompiledBindingPathBuilder(1).Property(XamlIlHelpers.DS1Randomizer.ViewModels.MainWindowViewModel,DS1Randomizer.Status!Property(), new Func<WeakReference<object>, IPropertyInfo, IPropertyAccessor>(PropertyInfoAccessorFactory.CreateInpcPropertyAccessor)).Build());
			IServiceProvider provider43 = context;
			context.ProvideTargetProperty = TextBlock.TextProperty;
			IBinding binding42 = compiledBindingExtension44.ProvideValue(provider43);
			context.ProvideTargetProperty = null;
			textBlock10.Bind(textProperty6, binding42, null);
			context.PopParent();
			supportInitialize53.EndInit();
			context.PopParent();
			supportInitialize.EndInit();
			context.PopParent();
			((ISupportInitialize)A_1).EndInit();
			StyledElement styled;
			if ((styled = (A_1 as StyledElement)) != null)
			{
				NameScope.SetNameScope(styled, context.AvaloniaNameScope);
			}
			context.AvaloniaNameScope.Complete();
		}

		// Token: 0x06000032 RID: 50 RVA: 0x00004527 File Offset: 0x00002727
		private static void !XamlIlPopulateTrampoline(MainWindow A_0)
		{
			if (MainWindow.!XamlIlPopulateOverride != null)
			{
				MainWindow.!XamlIlPopulateOverride(A_0);
				return;
			}
			MainWindow.!XamlIlPopulate(XamlIlRuntimeHelpers.CreateRootServiceProviderV3(null), A_0);
		}

		// Token: 0x04000018 RID: 24
		[Nullable(0)]
		[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.2.7.0")]
		internal TextBlock message;

		// Token: 0x04000019 RID: 25
		[Nullable(0)]
		[GeneratedCode("Avalonia.Generators.NameGenerator.InitializeComponentCodeGenerator", "11.2.7.0")]
		internal TextBlock status;

		// Token: 0x0400001A RID: 26
		private static Action<object> !XamlIlPopulateOverride;
	}
}
