namespace DS1Mod.Core.ImGui;

[Flags]
public enum ImGuiWindowFlags : int
{
    None                   = 0,
    NoTitleBar             = 1 << 0,
    NoResize               = 1 << 1,
    NoMove                 = 1 << 2,
    NoScrollbar            = 1 << 3,
    NoScrollWithMouse      = 1 << 4,
    NoCollapse             = 1 << 5,
    AlwaysAutoResize       = 1 << 6,
    NoBackground           = 1 << 7,
    NoSavedSettings        = 1 << 8,
    NoMouseInputs          = 1 << 9,
    MenuBar                = 1 << 10,
    HorizontalScrollbar    = 1 << 11,
    NoFocusOnAppearing     = 1 << 12,
    NoBringToDisplayOnFocus = 1 << 13,
    AlwaysVerticalScrollbar = 1 << 14,
    AlwaysHorizontalScrollbar = 1 << 15,
    NoNavInputs            = 1 << 16,
    NoNavFocus             = 1 << 17,
    UnsavedDocument        = 1 << 20,
    NoNav                  = NoNavInputs | NoNavFocus,
    NoDecoration           = NoTitleBar | NoResize | NoScrollbar | NoCollapse,
    NoInputs               = NoMouseInputs | NoNavInputs | NoNavFocus,
}

public enum ImGuiCond : int
{
    None         = 0,
    Always       = 1 << 0,
    Once         = 1 << 1,
    FirstUseEver = 1 << 2,
    Appearing    = 1 << 3,
}

public enum ImGuiCol : int
{
    Text                   = 0,
    TextDisabled           = 1,
    WindowBg               = 2,
    ChildBg                = 3,
    PopupBg                = 4,
    Border                 = 5,
    BorderShadow           = 6,
    FrameBg                = 7,
    FrameBgHovered         = 8,
    FrameBgActive          = 9,
    TitleBg                = 10,
    TitleBgActive          = 11,
    TitleBgCollapsed       = 12,
    MenuBarBg              = 13,
    ScrollbarBg            = 14,
    ScrollbarGrab          = 15,
    ScrollbarGrabHovered   = 16,
    ScrollbarGrabActive    = 17,
    CheckMark              = 18,
    SliderGrab             = 19,
    SliderGrabActive       = 20,
    Button                 = 21,
    ButtonHovered          = 22,
    ButtonActive           = 23,
    Header                 = 24,
    HeaderHovered          = 25,
    HeaderActive           = 26,
    Separator              = 27,
    SeparatorHovered       = 28,
    SeparatorActive        = 29,
    ResizeGrip             = 30,
    ResizeGripHovered      = 31,
    ResizeGripActive       = 32,
    TabHovered             = 33,
    Tab                    = 34,
    TabSelected            = 35,
    TabSelectedOverline    = 36,
    TabDimmed              = 37,
    TabDimmedSelected      = 38,
    TabDimmedSelectedOverline = 39,
    PlotLines              = 40,
    PlotLinesHovered       = 41,
    PlotHistogram          = 42,
    PlotHistogramHovered   = 43,
    TableHeaderBg          = 44,
    TableBorderStrong      = 45,
    TableBorderLight       = 46,
    TableRowBg             = 47,
    TableRowBgAlt          = 48,
    TextLink               = 49,
    TextSelectedBg         = 50,
    DragDropTarget         = 51,
    NavCursor              = 52,
    NavWindowingHighlight  = 53,
    NavWindowingDimBg      = 54,
    ModalWindowDimBg       = 55,
}
