<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DS1Mod.FartEntrance</AssemblyName>
    <RootNamespace>DS1Mod.FartEntrance</RootNamespace>
    <Description>The Asylum Demon farts the second he lands his entrance.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DS1Mod.SDK\DS1Mod.SDK.csproj" />
    <ProjectReference Include="..\..\SoulsFormats\SoulsFormats\SoulsFormats.csproj" />
  </ItemGroup>
</Project>
